name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.14.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true
          cache_dependency_path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm check:tsc

      - name: Lint
        run: pnpm check:lint

      - name: Format check
        run: pnpm check:format

      - name: Knip unused code check
        run: pnpm check:knip

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
